# Set sssd.conf file
[sssd]
domains = example.net
config_file_version = 2
services = nss, pam

[domain/example.net]
default_shell = /bin/bash
krb5_store_password_if_offline = True
cache_credentials = True
krb5_realm = EXAMPLE.NET
realmd_tags = manages-system joined-with-adcli
id_provider = ad
fallback_homedir = /home/%u
ad_domain = example.net
use_fully_qualified_names = False
ldap_id_mapping = True
access_provider = ad
ad_server = <ad_server_1>, <ad_server_2>
ad_backup_server = <ad_server_1>, <ad_server_2>
ad_site = <site_name>
ad_gpo_ignore_unreadable = True
ad_gpo_access_control = enforcing
ad_gpo_map_remote_interactive = +xrdp-sesman
ad_access_filter = (memberOf=cn=role-server admins,ou=administrator accounts,dc=example,dc=net)
