---
- name: Post-Install Config
  hosts: all
  become: yes
  ignore_errors: yes
  vars_files:
    - roles/sssd/vars/sssd.yaml
  roles:
    - tenable
    - crowdstrike
    - chronyd
    - sssd
    - cis_hardening

